/*******************************************************************************
 * Copyright (c) Faktor Zehn GmbH - faktorzehn.org
 * 
 * This source code is available under the terms of the AGPL Affero General Public License version
 * 3.
 * 
 * Please see LICENSE.txt for full license terms, including the additional permissions and
 * restrictions as well as the possibility of alternative license terms.
 *******************************************************************************/

/*
 * Generated By:JJTree: Do not edit this line.
 * C:/projekte/ips/workspace/org.faktorips.fl/src/org/faktorips/fl/parser\FlParserTreeConstants.java
 */

package org.faktorips.fl.parser;

public interface FlParserTreeConstants {
    int JJTSTART = 0;
    int JJTVOID = 1;
    int JJTEQNODE = 2;
    int JJTNOTEQNODE = 3;
    int JJTLTNODE = 4;
    int JJTGTNODE = 5;
    int JJTLENODE = 6;
    int JJTGENODE = 7;
    int JJTADDNODE = 8;
    int JJTSUBNODE = 9;
    int JJTMULTNODE = 10;
    int JJTDIVNODE = 11;
    int JJTPLUSNODE = 12;
    int JJTMINUSNODE = 13;
    int JJTNOTNODE = 14;
    int JJTPARENTHESISNODE = 15;
    int JJTFUNCTIONCALLNODE = 16;
    int JJTARGLISTNODE = 17;
    int JJTIDENTIFIERNODE = 18;
    int JJTBOOLEANNODE = 19;
    int JJTINTEGERNODE = 20;
    int JJTDECIMALNODE = 21;
    int JJTSTRINGNODE = 22;
    int JJTMONEYNODE = 23;
    int JJTNULLNODE = 24;

    String[] jjtNodeName = { "Start", "void", "EQNode", "NotEQNode", "LTNode", "GTNode", "LENode", "GENode",
            "AddNode", "SubNode", "MultNode", "DivNode", "PlusNode", "MinusNode", "NotNode", "ParenthesisNode",
            "FunctionCallNode", "ArgListNode", "IdentifierNode", "BooleanNode", "IntegerNode", "DecimalNode",
            "StringNode", "MoneyNode", "NullNode", };
}
