== Introduction

Faktor-IPS provides tool support for the development process of insurance-related IT systems. It is a modeling tool for model-driven software development with a user-friendly product system. Due to its high flexibility and extensibility there are hardly no limits to the diversity of possible applications.

For a brief introduction, take a look at the two short videos that we produced. You will get an overview of Faktor-IPS and how it works.

video::y-1QDLYkP0w[youtube]
video::3p7wx9KHGvI[youtube]

== Getting started...

As an Eclipse plugin, Faktor-IPS is seamlessly integrated in the established development environment. We also offer a simplified version of Faktor-IPS, which makes it easy for business departments to define products. A basic Eclipse installation is best suited for exploring Faktor-IPS. It allows you to define the models with Faktor-IPS and also to directly generate and edit the Java code. A manual for the installation is available under https://www.faktorzehn.org/en/download/[Download].

Upon successful installation of Faktor-IPS, we recommend watching our Faktor-IPS introductory video tutorials.

* https://doc.faktorzehn.org/tutorial/latest/html/[Introduction Tutorial Part 1 + Part 2] (Also available as https://doc.faktorzehn.org/tutorial/latest/documentation.pdf[PDF])
* https://doc.faktorzehn.org/tutorial/latest/Faktor-IPS-Tutorial-SampleSolution.zip[Sample Solution for the Tutorials as Maven Projects (ZIP)] +
You can import the sample solution via the import wizard “Existing Maven Projects”. If the projects do not yet correspond with the current Faktor-IPS version, you can trigger a migration by selecting “Faktor-IPS” from the drop-down list of the context menu.