== Modeling Business Classes

Since Faktor-IPS is based on the approach of model-driven software development, it is easy to create and maintain business models. The user interface offers numerous tools that will make you quickly feel at home—even with large and complex models. By offering multilingual labels and descriptions along with user-defined icons in the model, Faktor-IPS makes it easier for business departments to define products.

In the Faktor-IPS introduction tutorials, we designed the model for a “simplified” home insurance. In practice, the business models are of course more complex, especially if more than one line of business is mapped. For this reason, we would like to address here the partitioning of models. By model partitioning we mean the division of a complex complete model into smaller submodels.

* https://www.faktorzehn.org/fips-documentation/tutorial-modellpartitionierung.pdf[Tutorial: Model Partitioning (PDF)] - german only
* link:../../07_osgi_bundle/index.html[Faktor-IPS Projects as OSGi Bundles] - german only
* <<maven_en, Faktor-IPS Projects as Maven Dependencies>>
* <<archetype_en, Creating Faktor-IPS Projects as Maven Projects using Maven Archetypes>>
* https://www.faktorzehn.org/fips-documentation/tutorial-multi-language-support.pdf[Multilingual Models in Faktor-IPS (PDF)] - german only

For more information we recommend the article below, in which we explain how to define new data types that are not part of the Faktor-IPS standard version. You will also find detailed information on the different options you have for defining enumerations.

* https://www.faktorzehn.org/fips-documentation/faktorips-datentypen-und-aufzaehlungen.pdf[Data Types & Enumerations in Faktor-IPS (PDF)] - german only