== Integrating with Applications

The Java code of the generated and enhanced business model can be integrated in any Java SE or Java EE application.

This tutorial builds on the introduction tutorials. It shows how to build an application based on the business class models generated by Faktor-IPS and how to access the product data. In designing the application, we put special emphasis on ensuring that the application responds dynamically to product changes. Any product changes made by the business department in the context of the defined business model can be done while in productive use without having to modify the application. Furthermore, you will see how to ensure that the application responds flexibly to model changes. For purposes of illustration, we use a sample application, that is, a quotation system for calculating home insurances. It goes without saying that this is not a complete system. A partial view of the system suffices to explain the concepts. The system is a web application based on the RAP framework.

* https://www.faktorzehn.org/fips-documentation/tutorial-angebotsystem.pdf[Tutorial for Developing an Application (PDF)] - german only
* https://www.faktorzehn.org/fips-documentation/tutorial-angebotsystem.zip[Packaged RAP Application (ZIP)] for RAP 1.4/Eclipse 3.6 (requires the https://www.faktorzehn.org/fips-documentation/tutorial-projekte.zip[projects from the introduction tutorials (ZIP)])

With Faktor-IPS you can also choose to have the product data deployed separately from the program code of the application. See the following document for how that works and which challenges have to be tackled:

* https://www.faktorzehn.org/fips-documentation/separates-deployment-produkt-daten.pdf[Separate Deployment of Product Data (PDF)] - german only
* https://www.faktorzehn.org/fips-documentation/separates-deployment-produkt-daten.zip[Sample Projects for Separate Deployment of Product Data (ZIP)]

For more information on designing the interface of a product server, see the following article:

* https://www.faktorzehn.org/fips-documentation/f10-interface-design-for-product-servers.pdf[Interface Design for the Product Server (PDF)]