package org.faktorips.devtools.core.test;


import junit.framework.Test;
import junit.framework.TestSuite;

import org.faktorips.devtools.core.DefaultTestContent;
import org.faktorips.devtools.core.IpsPluginTest;
import org.faktorips.devtools.core.TestEnumType;
import org.faktorips.devtools.core.builder.DefaultBuilderSetTest;
import org.faktorips.devtools.core.builder.DependencyGraphTest;
import org.faktorips.devtools.core.builder.IpsBuilderTest;
import org.faktorips.devtools.core.builder.JavaSourceFileBuilderTest;
import org.faktorips.devtools.core.builder.JetJavaContentGeneratorTest;
import org.faktorips.devtools.core.builder.JetJavaSourceFileBuilderTest;
import org.faktorips.devtools.core.builder.TestIpsArtefactBuilderSet;
import org.faktorips.devtools.core.internal.model.AllValuesValueSetTest;
import org.faktorips.devtools.core.internal.model.ChangesOverTimeNamingConventionTest;
import org.faktorips.devtools.core.internal.model.DescriptionHelperTest;
import org.faktorips.devtools.core.internal.model.DynamicEnumDatatypeTest;
import org.faktorips.devtools.core.internal.model.DynamicValueDatatypeTest;
import org.faktorips.devtools.core.internal.model.EnumValueSetTest;
import org.faktorips.devtools.core.internal.model.IpsModelImplTest;
import org.faktorips.devtools.core.internal.model.IpsModelTest;
import org.faktorips.devtools.core.internal.model.IpsObjectGenerationTest;
import org.faktorips.devtools.core.internal.model.IpsObjectPartContainerTest;
import org.faktorips.devtools.core.internal.model.IpsObjectPartStateTest;
import org.faktorips.devtools.core.internal.model.IpsObjectPartTest;
import org.faktorips.devtools.core.internal.model.IpsObjectPathEntryTest;
import org.faktorips.devtools.core.internal.model.IpsObjectPathTest;
import org.faktorips.devtools.core.internal.model.IpsObjectTest;
import org.faktorips.devtools.core.internal.model.IpsObjectTestCase;
import org.faktorips.devtools.core.internal.model.IpsPackageFragmentRootTest;
import org.faktorips.devtools.core.internal.model.IpsPackageFragmentTest;
import org.faktorips.devtools.core.internal.model.IpsProjectPropertiesTest;
import org.faktorips.devtools.core.internal.model.IpsProjectRefEntryTest;
import org.faktorips.devtools.core.internal.model.IpsProjectTest;
import org.faktorips.devtools.core.internal.model.IpsSrcFileTest;
import org.faktorips.devtools.core.internal.model.IpsSrcFolderEntryTest;
import org.faktorips.devtools.core.internal.model.RangeValueSetTest;
import org.faktorips.devtools.core.internal.model.TestIpsObjectFactory;
import org.faktorips.devtools.core.internal.model.TimedIpsObjectTest;
import org.faktorips.devtools.core.internal.model.pctype.AttributeTest;
import org.faktorips.devtools.core.internal.model.pctype.MemberTest;
import org.faktorips.devtools.core.internal.model.pctype.MethodPluginTest;
import org.faktorips.devtools.core.internal.model.pctype.MethodTest;
import org.faktorips.devtools.core.internal.model.pctype.PolicyCmptTypeTest;
import org.faktorips.devtools.core.internal.model.pctype.RelationPluginTest;
import org.faktorips.devtools.core.internal.model.pctype.RelationTest;
import org.faktorips.devtools.core.internal.model.pctype.TypeHierarchyTest;
import org.faktorips.devtools.core.internal.model.pctype.ValidationRuleTest;
import org.faktorips.devtools.core.internal.model.product.AbstractProductCmptNamingStrategyTest;
import org.faktorips.devtools.core.internal.model.product.ConfigElementPluginTest;
import org.faktorips.devtools.core.internal.model.product.ConfigElementTest;
import org.faktorips.devtools.core.internal.model.product.DateBasedProductCmptNamingStrategyTest;
import org.faktorips.devtools.core.internal.model.product.DeepCopyOperationTest;
import org.faktorips.devtools.core.internal.model.product.DefaultRuntimeIdInitStrategyTest;
import org.faktorips.devtools.core.internal.model.product.NoVersionIdProductCmptNamingStrategyTest;
import org.faktorips.devtools.core.internal.model.product.ProductCmptGenerationPolicyCmptTypeDeltaTest;
import org.faktorips.devtools.core.internal.model.product.ProductCmptGenerationTest;
import org.faktorips.devtools.core.internal.model.product.ProductCmptRelationTest;
import org.faktorips.devtools.core.internal.model.product.ProductCmptStructureTest;
import org.faktorips.devtools.core.internal.model.product.ProductCmptTest;
import org.faktorips.devtools.core.internal.model.productcmpttype.ProductCmptTypeRelationTest;
import org.faktorips.devtools.core.internal.model.productcmpttype.ProductCmptTypeTest;
import org.faktorips.devtools.core.internal.model.tablecontents.RowImplTest;
import org.faktorips.devtools.core.internal.model.tablecontents.TableContentsGenerationImplTest;
import org.faktorips.devtools.core.internal.model.tablecontents.TableContentsImplPluginTest;
import org.faktorips.devtools.core.internal.model.tablecontents.TableContentsImplTest;
import org.faktorips.devtools.core.internal.model.tablestructure.ColumnImplTest;
import org.faktorips.devtools.core.internal.model.tablestructure.ColumnRangeImplTest;
import org.faktorips.devtools.core.internal.model.tablestructure.ForeignKeyImplTest;
import org.faktorips.devtools.core.internal.model.tablestructure.TableStructureTest;
import org.faktorips.devtools.core.internal.model.tablestructure.UniqueKeyImplTest;
import org.faktorips.devtools.core.internal.refactor.MoveOperationTest;
import org.faktorips.devtools.core.model.PdObjectTypeTest;
import org.faktorips.devtools.core.model.QualifiedNameTypeTest;
import org.faktorips.devtools.core.model.ValueSetTypeTest;
import org.faktorips.devtools.core.model.extproperties.IpsObjectPartStringExtPropertyTest;
import org.faktorips.devtools.core.model.pctype.ModifierTest;
import org.faktorips.devtools.core.ui.SimpleDialogTest;
import org.faktorips.devtools.core.ui.actions.IpsCutActionTest;
import org.faktorips.devtools.core.ui.actions.IpsPasteActionTest;
import org.faktorips.devtools.core.ui.editors.pctype.ValidatedAttributesCompletionProcessorTest;
import org.faktorips.devtools.core.ui.editors.productcmpt.FormulaCompletionProcessorTest;

public class AutomatedSuite extends TestSuite {
	public static Test suite(){
		
		TestSuite suite = new TestSuite();

		suite.addTestSuite(ValueSetTypeTest.class);
		suite.addTestSuite(PdObjectTypeTest.class);
		suite.addTestSuite(QualifiedNameTypeTest.class);
		suite.addTestSuite(IpsObjectPartStringExtPropertyTest.class);
		suite.addTestSuite(ModifierTest.class);
		suite.addTestSuite(ProductCmptTypeRelationTest.class);
		suite.addTestSuite(ProductCmptTypeTest.class);
		suite.addTestSuite(DynamicValueDatatypeTest.class);
		suite.addTestSuite(IpsObjectPathEntryTest.class);
		suite.addTestSuite(IpsObjectTest.class);
		suite.addTestSuite(AllValuesValueSetTest.class);
		suite.addTestSuite(IpsPackageFragmentRootTest.class);
		suite.addTestSuite(IpsObjectGenerationTest.class);
		suite.addTestSuite(EnumValueSetTest.class);
		suite.addTestSuite(IpsModelImplTest.class);
		suite.addTestSuite(DescriptionHelperTest.class);
		suite.addTestSuite(IpsProjectTest.class);
		suite.addTestSuite(TimedIpsObjectTest.class);
		suite.addTestSuite(IpsObjectPartStateTest.class);
		suite.addTestSuite(RangeValueSetTest.class);
		suite.addTestSuite(IpsObjectPartContainerTest.class);
		suite.addTestSuite(IpsSrcFolderEntryTest.class);
		suite.addTestSuite(IpsProjectRefEntryTest.class);
		suite.addTestSuite(IpsObjectPartTest.class);
		suite.addTestSuite(IpsModelTest.class);
		suite.addTestSuite(IpsProjectPropertiesTest.class);
		suite.addTestSuite(IpsPackageFragmentTest.class);
		suite.addTestSuite(DynamicEnumDatatypeTest.class);
		suite.addTestSuite(ChangesOverTimeNamingConventionTest.class);
		suite.addTestSuite(IpsObjectPathTest.class);
		suite.addTestSuite(IpsSrcFileTest.class);
		suite.addTestSuite(TableContentsGenerationImplTest.class);
		suite.addTestSuite(TableContentsImplTest.class);
		suite.addTestSuite(TableContentsImplPluginTest.class);
		suite.addTestSuite(RowImplTest.class);
		suite.addTestSuite(ProductCmptGenerationPolicyCmptTypeDeltaTest.class);
		suite.addTestSuite(ProductCmptTest.class);
		suite.addTestSuite(ProductCmptStructureTest.class);
		suite.addTestSuite(DefaultRuntimeIdInitStrategyTest.class);
		suite.addTestSuite(DeepCopyOperationTest.class);
		suite.addTestSuite(ConfigElementPluginTest.class);
		suite.addTestSuite(ProductCmptRelationTest.class);
		suite.addTestSuite(ProductCmptGenerationTest.class);
		suite.addTestSuite(NoVersionIdProductCmptNamingStrategyTest.class);
		suite.addTestSuite(DateBasedProductCmptNamingStrategyTest.class);
		suite.addTestSuite(ConfigElementTest.class);
		suite.addTestSuite(ColumnImplTest.class);
		suite.addTestSuite(UniqueKeyImplTest.class);
		suite.addTestSuite(ColumnRangeImplTest.class);
		suite.addTestSuite(ForeignKeyImplTest.class);
		suite.addTestSuite(TableStructureTest.class);
		suite.addTestSuite(TypeHierarchyTest.class);
		suite.addTestSuite(MethodTest.class);
		suite.addTestSuite(AttributeTest.class);
		suite.addTestSuite(PolicyCmptTypeTest.class);
		suite.addTestSuite(MemberTest.class);
		suite.addTestSuite(ValidationRuleTest.class);
		suite.addTestSuite(RelationPluginTest.class);
		suite.addTestSuite(MethodPluginTest.class);
		suite.addTestSuite(RelationTest.class);
		suite.addTestSuite(MoveOperationTest.class);
		suite.addTestSuite(JetJavaSourceFileBuilderTest.class);
		suite.addTestSuite(DependencyGraphTest.class);
		suite.addTestSuite(JetJavaContentGeneratorTest.class);
		suite.addTestSuite(JavaSourceFileBuilderTest.class);
		suite.addTestSuite(IpsBuilderTest.class);
		suite.addTestSuite(DefaultBuilderSetTest.class);
		suite.addTestSuite(IpsCutActionTest.class);
		suite.addTestSuite(IpsPasteActionTest.class);
		suite.addTestSuite(SimpleDialogTest.class);
		suite.addTestSuite(FormulaCompletionProcessorTest.class);
		suite.addTestSuite(ValidatedAttributesCompletionProcessorTest.class);

		return suite;
	}
	
}
