/*******************************************************************************
 * Copyright (c) Faktor Zehn GmbH - faktorzehn.org
 *
 * This source code is available under the terms of the AGPL Affero General Public License version
 * 3.
 *
 * Please see LICENSE.txt for full license terms, including the additional permissions and
 * restrictions as well as the possibility of alternative license terms.
 *******************************************************************************/

package org.faktorips.devtools.stdbuilder;

import org.faktorips.devtools.model.internal.productcmpt.IImplementationClassProvider;
import org.faktorips.devtools.model.productcmpt.IProductCmpt;

/**
 * An {@link IImplementationClassProvider} that returns the Java class name generated by this
 * builder.
 */
public class StdBuilderImplementationClassProvider implements IImplementationClassProvider {

    @Override
    public String getImplementationClassQualifiedName(IProductCmpt productCmpt) {
        return ((StandardBuilderSet)productCmpt.getIpsProject().getIpsArtefactBuilderSet())
                .getProductCmptBuilder()
                .getImplementationClass(productCmpt);
    }

}
