/*******************************************************************************
 * Copyright (c) Faktor Zehn GmbH - faktorzehn.org
 *
 * This source code is available under the terms of the AGPL Affero General Public License version
 * 3.
 *
 * Please see LICENSE.txt for full license terms, including the additional permissions and
 * restrictions as well as the possibility of alternative license terms.
 *******************************************************************************/

package org.faktorips.devtools.model.builder.base;

import org.faktorips.devtools.model.ipsobject.IIpsObject;
import org.faktorips.devtools.model.ipsobject.IIpsObjectPart;
import org.faktorips.devtools.model.ipsobject.IIpsSrcFile;
import org.faktorips.devtools.model.ipsproject.IIpsArtefactBuilder;

/**
 * An implementation of {@link IIpsArtefactBuilder} that generates a source file for a specific
 * IpsObject. It has methods to get a qualified name for the generated object.
 */
public interface ISourceFileBuilder extends IIpsArtefactBuilder {

    /**
     * Returns the qualified name of the Java class generated by this builder for the IPS object
     * stored in the given IPS source file.
     *
     * @param ipsSrcFile the IPS source file.
     *
     */
    String getQualifiedClassName(IIpsSrcFile ipsSrcFile);

    /**
     * Returns the qualified name of the Java class generated by this builder for the given IPS
     * object.
     *
     * @param ipsObject the IPS object.
     */
    default String getQualifiedClassName(IIpsObject ipsObject) {
        return getQualifiedClassName(ipsObject.getIpsSrcFile());
    }

    /**
     * Returns the qualified name of the Java class generated by this builder for the given IPS
     * object part.
     *
     * @param ipsObjectPart the IPS object part.
     */
    default String getQualifiedClassName(IIpsObjectPart ipsObjectPart) {
        return getQualifiedClassName(ipsObjectPart.getIpsObject());
    }

}