:jbake-title: Fachliche Klassen modellieren
:jbake-type: section
:jbake-status: published

== Fachliche Klassen modellieren

Faktor-IPS bietet nach dem Ansatz der modellgetriebenen Softwareentwicklung die Möglichkeit, fachliche Modelle einfach zu erstellen und zu pflegen. Die Benutzeroberfläche bietet zahlreiche Tools, um sich auch in großen, komplexen Modellen schnell zurechtzufinden. Durch die Angaben von mehrsprachigen Labels und Beschreibungen sowie benutzerdefinierte Icons wird bereits im Modell die Eingabe von Produkten für den Fachbereich vorbereitet und erleichtert.

In den Faktor-IPS-Einführungstutorials haben wir das Modell für eine einfache Hausratversicherung entworfen. In der Praxis sind die fachlichen Modelle natürlich wesentlich komplexer, insbesondere wenn mehrere Sparten abgebildet werden. In den folgenden Dokumenten wollen wir daher auf die Partitionierung von Modellen eingehen. Unter Modellpartitionierung verstehen wir die Zerlegung eines komplexen Gesamtmodells in kleinere Teilmodelle.

* https://www.faktorzehn.org/fips-documentation/tutorial-modellpartitionierung.pdf[Tutorial: Modellpartitionierung (PDF)]

Als weiterführende Dokumentation empfehlen wir den folgenden Artikel, in dem erklärt wird, wie neue Datentypen definiert werden können, die nicht zum Standardumfang von Faktor-IPS gehören. Darüber hinaus werden ausführlich die Möglichkeiten zur Definition von Aufzählungen erläutert.

* https://www.faktorzehn.org/fips-documentation/faktorips-datentypen-und-aufzaehlungen.pdf[Datentypen & Aufzählungen in Faktor-IPS (PDF)]

Informationen über die Relevanz eines Attributs sind nützlich, um es in einem User Interface sinnvoll darzustellen. So können beispielsweise irrelevante Attribute ausgeblendet werden und Pflichtfelder als solche markiert werden.

* <<relevanzen, Relevanzen>>

Weitere Dokumentation zur Einrichtung von Projekten und Umgang mit dem generierten Code:

* <<osgi, Faktor-IPS-Projekte als OSGi Bundles>>
* <<maven, Faktor-IPS-Projekte als Maven-Dependencies>>
* <<archetype, Faktor-IPS-Projekte als Maven-Projekte mittels Maven-Archetypes erstellen>>
* https://www.faktorzehn.org/fips-documentation/tutorial-multi-language-support.pdf[Mehrsprachige Modelle mit Faktor-IPS (PDF)]