:jbake-title: Java-Code generieren
:jbake-type: section
:jbake-status: published

== Java-Code generieren

Direkt mit dem Speichern einer Modellklasse wird inkrementell Java-Code generiert. Dabei ist es jederzeit möglich, Änderungen im Java-Code vorzunehmen oder das Modell zu verändern und zu erweitern. Die generierten Artefakte werden mit dem manuellen Code zusammengeführt. Der generierte Code erhöht durch eine einheitliche Generierung die Codequalität.

* <<manuelle_anpassungen, Dokumentation zur Anpassungen des generierten Codes>>

Zusätzlich zu den Modellklassen werden Builder-Klassen generiert um Modelle zu instantiieren. Durch die Verwendung dieser einheitlichen Builder Klassen wird die Softwarequalität und Codeverständlichkeit gleichermaßen erhöht.

* <<builder, Generierte Builder für Vertrags- und Produktteilklassen>>

Um auch zur Laufzeit über den generierten Code auf die Informationen des erstellten Modells zugreifen zu können, bietet das Faktor-IPS Metamodell eine praktische Schnittstelle, die in dieser Dokumentation genauer beschrieben wird:

* <<metamodell, Faktor-IPS Metamodell: Modellinformationen zur Runtime>>