:jbake-title: Produkte definieren
:jbake-type: section
:jbake-status: published

== Produkte definieren

Versicherungsprodukte werden von Fachanwendern in benutzerfreundlichen Editoren erstellt und gewartet. Die Basis bilden die vorher definierten Modelle.

Für die Produktdefinition bietet Faktor-IPS eine eigene Testunterstützung. Diese umfasst sowohl die Definition als auch die Ausführung von Testfällen. Dieses Tutorial beschreibt die zugrunde liegenden Konzepte. Anhand eines Beispiels wird der Umgang mit den Faktor-IPS-Testwerkzeugen gezeigt und deren Funktionsweise erläutert.

* https://www.faktorzehn.org/fips-documentation/tutorial-testen.pdf[Tutorial: Softwaretests mit Faktor-IPS (PDF)]

Wenn die Produkte größer und vielfältiger werden, wird es zunehmend komplexer die steigende Anzahl der Produktbausteine zu warten. Um diese Aufgabe zu bewältigen, wurden die Produktvorlagen entwickelt. Mit Produktvorlagen können bausteinübergreifende Definitionen elegant und effizient verwaltet werden. Und das nicht nur für neu aufzubauende Produktdefinitionen, sondern auch bereits bestehende Produktwelten können analysiert und daraus Kandidaten für übergreifende Produktvorlagen identifiziert werden.

* https://www.faktorzehn.org/fips-documentation/faktorips-vorlagen.pdf[Produktvorlagen (PDF)]