:jbake-title: In Anwendungen integrieren
:jbake-type: section
:jbake-status: published

== In Anwendungen integrieren

Der Java-Code des generierten und erweiterten Fachmodell kann in eine beliebige Java-SE- oder Java-EE-Anwendung integriert werden.

Dieses Tutorial setzt auf den Einführungstutorials auf. Es zeigt, wie man eine Anwendung auf Basis der von Faktor-IPS generierten Fachmodellklassen baut und wie auf die Produktdaten zugegriffen werden kann. Besonderer Wert wird dabei im Design darauf gelegt, dass die Anwendung dynamisch auf Produktänderungen reagiert. Produktänderungen durch die Fachabteilung im Rahmen des definierten Fachmodells sollen produktiv genutzt werden, ohne dass die Anwendung geändert werden muss. Des Weiteren wird gezeigt, wie man die Anwendung auch flexibel auf Modelländerungen reagieren lassen kann. Als Beispielanwendung dient ein Angebotssystem mit dem Hausratversicherungen berechnet werden können. Dabei handelt es sich natürlich nicht um ein vollständiges System, sondern um einen Ausschnitt anhand dessen die Konzepte erläutert werden. Bei dem System handelt es sich um eine Webanwendung auf Basis des RAP-Frameworks.

* https://www.faktorzehn.org/fips-documentation/tutorial-angebotsystem.pdf[Tutorial zur Entwicklung einer Anwendung (PDF)]
* https://www.faktorzehn.org/fips-documentation/tutorial-angebotsystem.zip[Fertige RAP-Anwendung (ZIP)] für RAP 1.4/Eclipse 3.6 (benötigt die https://www.faktorzehn.org/fips-documentation/tutorial-projekte.zip[Projekte aus den Einführungstutorials (ZIP)])

Faktor-IPS bietet außerdem die Möglichkeit, Produktdaten getrennt vom Programmcode der Applikation auszuliefern. Wie das funktioniert und welche Herausforderungen dabei zu bewältigen sind, wird in diesem Dokument erläutert.

* https://www.faktorzehn.org/fips-documentation/separates-deployment-produkt-daten.pdf[Separates Deployment von Produktdaten (PDF)]
* https://www.faktorzehn.org/fips-documentation/separates-deployment-produkt-daten.zip[Beispielprojekte zu Separates Deployment von Produktdaten (ZIP)]

Das Design der Schnittstelle eines Produktservers wird in folgendem Artikel erläutert und bewertet.

* https://www.faktorzehn.org/fips-documentation/faktorips-interface-produktserver.pdf[Schnittstellen-Design für Produktserver (PDF)]