/*******************************************************************************
 * Copyright (c) 2005-2009 Faktor Zehn AG und andere.
 * 
 * Alle Rechte vorbehalten.
 * 
 * Dieses Programm und alle mitgelieferten Sachen (Dokumentationen, Beispiele, Konfigurationen,
 * etc.) duerfen nur unter den Bedingungen der Faktor-Zehn-Community Lizenzvereinbarung - Version
 * 0.1 (vor Gruendung Community) genutzt werden, die Bestandteil der Auslieferung ist und auch unter
 * http://www.faktorzehn.org/f10-org:lizenzen:community eingesehen werden kann.
 * 
 * Mitwirkende: Faktor Zehn AG - initial API and implementation - http://www.faktorzehn.de
 *******************************************************************************/

package org.faktorips.devtools.stdbuilder.policycmpttype;

import java.util.Locale;

import org.eclipse.core.runtime.CoreException;
import org.faktorips.devtools.core.builder.DefaultJavaGeneratorForIpsPart;
import org.faktorips.devtools.core.model.ipsobject.IIpsObjectPartContainer;
import org.faktorips.devtools.core.model.ipsproject.IIpsProject;
import org.faktorips.devtools.core.model.pctype.IPolicyCmptType;
import org.faktorips.devtools.stdbuilder.StandardBuilderSet;
import org.faktorips.util.ArgumentCheck;
import org.faktorips.util.LocalizedStringsSet;

public abstract class GenPolicyCmptTypePart extends DefaultJavaGeneratorForIpsPart {

    private GenPolicyCmptType genPolicyCmptType;

    public GenPolicyCmptTypePart(GenPolicyCmptType genPolicyCmptType, IIpsObjectPartContainer part,
            LocalizedStringsSet stringsSet) throws CoreException {
        super(part, stringsSet);
        ArgumentCheck.notNull(genPolicyCmptType, this);
        this.genPolicyCmptType = genPolicyCmptType;
    }

    public GenPolicyCmptType getGenPolicyCmptType() {
        return genPolicyCmptType;
    }

    public StandardBuilderSet getBuilderSet() {
        return genPolicyCmptType.getBuilderSet();
    }

    protected IIpsProject getIpsProject() {
        return getGenPolicyCmptType().getPolicyCmptType().getIpsProject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Locale getLanguageUsedInGeneratedSourceCode() {
        return genPolicyCmptType.getLanguageUsedInGeneratedSourceCode();
    }

    /**
     * Returns the qualified name of the Java class generated by this builder for the given ips
     * object.
     * 
     * @param ipsObject the ips object.
     * @return the qualified class name
     * @throws CoreException
     */
    public String getQualifiedClassName(IPolicyCmptType target, boolean forInterface) throws CoreException {
        return genPolicyCmptType.getBuilderSet().getGenerator(target).getQualifiedName(forInterface);
    }

    public String getUnqualifiedClassName(IPolicyCmptType target, boolean forInterface) throws CoreException {
        return genPolicyCmptType.getBuilderSet().getGenerator(target).getUnqualifiedClassName(forInterface);
    }

    protected boolean isUseTypesafeCollections() {
        return getGenPolicyCmptType().getBuilderSet().isUseTypesafeCollections();
    }

    protected boolean isGenerateJaxbSupport() {
        return getGenPolicyCmptType().getBuilderSet().isGenerateJaxbSupport();
    }
}
