/* Generated By:JJTree: Do not edit this line. ASTBooleanNode.java */

package org.faktorips.fl.parser;

public class ASTBooleanNode extends SimpleNode {
  public ASTBooleanNode(int id) {
    super(id);
  }

  public ASTBooleanNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
