/* Generated By:JJTree: Do not edit this line. ASTDecimalNode.java */

package org.faktorips.fl.parser;

public class ASTDecimalNode extends SimpleNode {
  public ASTDecimalNode(int id) {
    super(id);
  }

  public ASTDecimalNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
