/* Generated By:JJTree: Do not edit this line. ASTFunctionCallNode.java */

package org.faktorips.fl.parser;

public class ASTFunctionCallNode extends SimpleNode {
  public ASTFunctionCallNode(int id) {
    super(id);
  }

  public ASTFunctionCallNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
