/* Generated By:JJTree: Do not edit this line. ASTMultNode.java */

package org.faktorips.fl.parser;

public class ASTMultNode extends SimpleNode {
  public ASTMultNode(int id) {
    super(id);
  }

  public ASTMultNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
