/* Generated By:JJTree: Do not edit this line. ASTMoneyNode.java */

package org.faktorips.fl.parser;

public class ASTMoneyNode extends SimpleNode {
  public ASTMoneyNode(int id) {
    super(id);
  }

  public ASTMoneyNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
