/* Generated By:JJTree: Do not edit this line. ASTNotEQNode.java */

package org.faktorips.fl.parser;

public class ASTNotEQNode extends SimpleNode {
  public ASTNotEQNode(int id) {
    super(id);
  }

  public ASTNotEQNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
