/* Generated By:JJTree: Do not edit this line. ASTNotNode.java */

package org.faktorips.fl.parser;

public class ASTNotNode extends SimpleNode {
  public ASTNotNode(int id) {
    super(id);
  }

  public ASTNotNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
