/* Generated By:JJTree: Do not edit this line. ASTPlusNode.java */

package org.faktorips.fl.parser;

public class ASTPlusNode extends SimpleNode {
  public ASTPlusNode(int id) {
    super(id);
  }

  public ASTPlusNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
