/* Generated By:JJTree: Do not edit this line. ASTSubNode.java */

package org.faktorips.fl.parser;

public class ASTSubNode extends SimpleNode {
  public ASTSubNode(int id) {
    super(id);
  }

  public ASTSubNode(FlParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(FlParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
