/*******************************************************************************
 * Copyright (c) 2005-2011 Faktor Zehn AG und andere.
 * 
 * Alle Rechte vorbehalten.
 * 
 * Dieses Programm und alle mitgelieferten Sachen (Dokumentationen, Beispiele, Konfigurationen,
 * etc.) duerfen nur unter den Bedingungen der Faktor-Zehn-Community Lizenzvereinbarung - Version
 * 0.1 (vor Gruendung Community) genutzt werden, die Bestandteil der Auslieferung ist und auch unter
 * http://www.faktorzehn.org/fips:lizenz eingesehen werden kann.
 * 
 * Mitwirkende: Faktor Zehn AG - initial API and implementation - http://www.faktorzehn.de
 *******************************************************************************/

/*
 * Generated By:JJTree: Do not edit this line.
 * C:/projekte/ips/workspace/org.faktorips.fl/src/org/faktorips/fl/parser\FlParserTreeConstants.java
 */

package org.faktorips.fl.parser;

public interface FlParserTreeConstants {
    public int JJTSTART = 0;
    public int JJTVOID = 1;
    public int JJTEQNODE = 2;
    public int JJTNOTEQNODE = 3;
    public int JJTLTNODE = 4;
    public int JJTGTNODE = 5;
    public int JJTLENODE = 6;
    public int JJTGENODE = 7;
    public int JJTADDNODE = 8;
    public int JJTSUBNODE = 9;
    public int JJTMULTNODE = 10;
    public int JJTDIVNODE = 11;
    public int JJTPLUSNODE = 12;
    public int JJTMINUSNODE = 13;
    public int JJTNOTNODE = 14;
    public int JJTPARENTHESISNODE = 15;
    public int JJTFUNCTIONCALLNODE = 16;
    public int JJTARGLISTNODE = 17;
    public int JJTIDENTIFIERNODE = 18;
    public int JJTBOOLEANNODE = 19;
    public int JJTINTEGERNODE = 20;
    public int JJTDECIMALNODE = 21;
    public int JJTSTRINGNODE = 22;
    public int JJTMONEYNODE = 23;
    public int JJTNULLNODE = 24;

    public String[] jjtNodeName = { "Start", "void", "EQNode", "NotEQNode", "LTNode", "GTNode", "LENode", "GENode",
            "AddNode", "SubNode", "MultNode", "DivNode", "PlusNode", "MinusNode", "NotNode", "ParenthesisNode",
            "FunctionCallNode", "ArgListNode", "IdentifierNode", "BooleanNode", "IntegerNode", "DecimalNode",
            "StringNode", "MoneyNode", "NullNode", };
}
