/*******************************************************************************
 * Copyright (c) 2005-2010 Faktor Zehn AG und andere.
 * 
 * Alle Rechte vorbehalten.
 * 
 * Dieses Programm und alle mitgelieferten Sachen (Dokumentationen, Beispiele, Konfigurationen,
 * etc.) duerfen nur unter den Bedingungen der Faktor-Zehn-Community Lizenzvereinbarung - Version
 * 0.1 (vor Gruendung Community) genutzt werden, die Bestandteil der Auslieferung ist und auch unter
 * http://www.faktorzehn.org/fips:lizenz eingesehen werden kann.
 * 
 * Mitwirkende: Faktor Zehn AG - initial API and implementation - http://www.faktorzehn.de
 *******************************************************************************/

/*
 * Generated By:JJTree: Do not edit this line.
 * C:/projekte/ips/workspace/org.faktorips.fl/src/org/faktorips/fl/parser\FlParserVisitor.java
 */

package org.faktorips.fl.parser;

public interface FlParserVisitor {
    public Object visit(SimpleNode node, Object data);

    public Object visit(ASTStart node, Object data);

    public Object visit(ASTEQNode node, Object data);

    public Object visit(ASTNotEQNode node, Object data);

    public Object visit(ASTLTNode node, Object data);

    public Object visit(ASTGTNode node, Object data);

    public Object visit(ASTLENode node, Object data);

    public Object visit(ASTGENode node, Object data);

    public Object visit(ASTAddNode node, Object data);

    public Object visit(ASTSubNode node, Object data);

    public Object visit(ASTMultNode node, Object data);

    public Object visit(ASTDivNode node, Object data);

    public Object visit(ASTPlusNode node, Object data);

    public Object visit(ASTMinusNode node, Object data);

    public Object visit(ASTNotNode node, Object data);

    public Object visit(ASTParenthesisNode node, Object data);

    public Object visit(ASTFunctionCallNode node, Object data);

    public Object visit(ASTArgListNode node, Object data);

    public Object visit(ASTIdentifierNode node, Object data);

    public Object visit(ASTBooleanNode node, Object data);

    public Object visit(ASTIntegerNode node, Object data);

    public Object visit(ASTDecimalNode node, Object data);

    public Object visit(ASTStringNode node, Object data);

    public Object visit(ASTMoneyNode node, Object data);

    public Object visit(ASTNullNode node, Object data);
}
