/*******************************************************************************
 * Copyright (c) 2005-2012 Faktor Zehn AG und andere.
 * 
 * Alle Rechte vorbehalten.
 * 
 * Dieses Programm und alle mitgelieferten Sachen (Dokumentationen, Beispiele, Konfigurationen,
 * etc.) duerfen nur unter den Bedingungen der Faktor-Zehn-Community Lizenzvereinbarung - Version
 * 0.1 (vor Gruendung Community) genutzt werden, die Bestandteil der Auslieferung ist und auch unter
 * http://www.faktorzehn.org/f10-org:lizenzen:community eingesehen werden kann.
 * 
 * Mitwirkende: Faktor Zehn AG - initial API and implementation - http://www.faktorzehn.de
 *******************************************************************************/

package org.faktorips.devtools.stdbuilder.flidentifier;

import org.faktorips.codegen.JavaCodeFragment;
import org.faktorips.datatype.Datatype;
import org.faktorips.datatype.ListOfTypeDatatype;
import org.faktorips.devtools.core.builder.flidentifier.AbstractIdentifierNodeGenerator;
import org.faktorips.devtools.core.builder.flidentifier.IdentifierNodeGeneratorFactory;
import org.faktorips.devtools.core.builder.flidentifier.ast.InvalidIdentifierNode;
import org.faktorips.devtools.core.model.ipsobject.IIpsObjectPartContainer;
import org.faktorips.devtools.core.model.ipsproject.IIpsProject;
import org.faktorips.devtools.stdbuilder.StandardBuilderSet;
import org.faktorips.devtools.stdbuilder.xpand.model.AbstractGeneratorModelNode;
import org.faktorips.fl.CompilationResult;
import org.faktorips.fl.CompilationResultImpl;

public abstract class AbstractIdentifierGenerator extends AbstractIdentifierNodeGenerator<JavaCodeFragment> {

    private final StandardBuilderSet builderSet;

    public AbstractIdentifierGenerator(IdentifierNodeGeneratorFactory<JavaCodeFragment> factory,
            StandardBuilderSet builderSet) {
        super(factory);
        this.builderSet = builderSet;
    }

    protected <X extends AbstractGeneratorModelNode> X getModelNode(IIpsObjectPartContainer container, Class<X> type) {
        return getBuilderSet().getModelNode(container, type);
    }

    @Override
    protected CompilationResult<JavaCodeFragment> getErrorCompilationResult(InvalidIdentifierNode invalidIdentifierNode) {
        return new CompilationResultImpl(invalidIdentifierNode.getMessage());
    }

    protected StandardBuilderSet getBuilderSet() {
        return builderSet;
    }

    /**
     * Returns the {@link StandardBuilderSet StandardBuilderSets} project.
     */
    protected IIpsProject getIpsProject() {
        return getBuilderSet().getIpsProject();
    }

    /**
     * Returns whether the given {@link CompilationResult compilation result's} code would return a
     * list of objects in contrast to a single object. E.g. a list of policy objects or attribute
     * values instead of a single policy object or attribute value.
     * 
     * @param contextCompilationResult the compilation result whose return type should be tested
     * @return <code>true</code> if the compilation result's datatype is a list datatype,
     *         <code>false</code> otherwise.
     */
    protected boolean isListDatatypeContext(CompilationResult<JavaCodeFragment> contextCompilationResult) {
        return contextCompilationResult.getDatatype() instanceof ListOfTypeDatatype;
    }

    /**
     * Returns the java class name for the given datatype. For policy- and product component types
     * the names of the classes generated by the standard builder are returned.
     */
    public String getJavaClassName(Datatype datatype) {
        return getBuilderSet().getJavaClassName(datatype, true);
    }

}
