:jbake-title: Release Notes (English)
:jbake-type: chapter
:jbake-status: published
:jbake-order: 20
:images-folder: {images}releasenotes/

== Release Notes (English)

=== Version 21.12.0

==== New Features and Improvements

[[unified_valueset_methods]]
===== Unified Value-Set Methods (https://jira.faktorzehn.de/browse/FIPS-6497[FIPS-6497])
The methods to query value sets for attributes configured in the model or products had two problems:

 * they were named differently depending on the type of value set (for example `getRangeForLivingSpace`,`getSetOfAllowedValuesForPaymentMode`,`getAllowedValuesForDisplacement`). The original intention was to see the type of value set from the method name, but that meant already knowing the method name. When programming it turned out to be more common to only know an attribute's name but not it's value set type.
 * they required a ValidationContext parameter which was then not used in the generated code, which led to warnings in the code. to use the context to specify different value sets depending on context information, but this way it was not possible to configure this in the products. 
That meant having to know the type of value set to be able to call the matching method (or generically using the `IpsModel`) and supplying an unnecessary ValidationContext or `null`. 
From Faktor-IPS 22.6 onward, the generator can now be configured to use a unified method name(`getAllowedValuesForLivingSpace`) for all types of value sets and omit the context parameter. This also makes overwriting value sets for derived value sets easier.
Upon migration you can choose to switch to the new unified methods(`Unified`), keep the old methods(`ByValueSetType`) or generate both methods(`Both`). 

Faktor-IPS even supports different `valueSetMethods` per project. However, this feature should be used sparsely because the code generator must create additional similar methods so that the java inheritance continues to work as expected.
Also we recommend using the `Both` setting only for migration purposes, but not for the productive code.

If some value set methods were already manually edited, we suggest the following migration workflow:

 . Change your base model to `Both`
 . Copy all manual code to the new methods
 . Change line-of-business-models to `Both`
 . Copy all manual code to the new methods
 . Change line-of-business-models to `Unified`
 . Change your base model to `Unified`
  
WARNING: For Maven or OSGi projects, the setting `valueSetMethods` should be configured not only in the `.ipsproject` file but also in the `META-INF/MANIFEST.MF`. If that file exists, the migration adds or replaces the `Fips-GeneratorConfig` section with the current values. When later changing the setting for `valueSetMethods` it must be manually synchronized. The setting from the manifest is used by the code generator when a referenced project (e.g. the base model) is only referenced as a dependency but not opened as a project in the workspace.
 
Remaining calls to the old methods in handwritten code parts can be replaced with regular expressions, for example use in Eclipse `\.get(?:Range|(?:SetOf)AllowedValues)For([^(]+)\((?:[^)(]+|\((?:[^)(]+|\([^)(]*\))*\))*\)` to be replaced with `.getAllowedValuesFor$1()`.
 
===== Migration
When migrating to Faktor-IPS 22.6, generation of value-set methods can be changed as described in section <<unified_valueset_methods, Unified Value-Set Methods>>.


===== Further Features and Improvements

 * [...]

==== Fixed Bugs
 * [...]
 